# generated by datamodel-codegen:
#   filename:  config.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Config(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    youtube_api_key: str
    litellm_uri: str
    litellm_api_key: str
    notes_triage_location: str
