# generated by datamodel-codegen:
#   filename:  config.schema.json

from __future__ import annotations

from pathlib import Path
from typing import Optional

from pydantic import BaseModel, ConfigDict, field_validator


class Config(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    youtube_api_key: Optional[str] = None
    youtube_api_key_path: Optional[str] = None
    openai_uri: str
    openai_api_key: str
    model: str
    notes_triage_location: str

    @field_validator("youtube_api_key", "youtube_api_key_path")
    @classmethod
    def validate_youtube_key(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return v
        if not v.strip():
            raise ValueError("must not be empty")
        return v.strip()

    def resolve_youtube_api_key(self) -> str:
        key = self.youtube_api_key
        if key is None and self.youtube_api_key_path is not None:
            path = Path(self.youtube_api_key_path).expanduser()
            key = path.read_text().strip()
        if key is None:
            raise ValueError(
                "Either 'youtube_api_key' or 'youtube_api_key_path' must be set in config"
            )
        return key
